//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MUTWndApp.rc
//
#define IDD_FLATULTDEMO_DIALOG          102
#define IDD_FLATULT_DLG                 102
#define IDR_HTML_RUNBTMWND              103
#define IDD_APPLY_DLG                   129
#define IDD_SCANB_DLG                   130
#define IDD_APPLY_MENU                  131
#define IDD_ABOUT_DLG                   132
#define IDD_DOCTOR_DLG                  133
#define IDD_PATIENT_DLG                 134
#define IDB_BMP_SOC                     140
#define IDD_SWND_RUN_LEFT               150
#define IDD_SWND_FRZE_LEFT              151
#define IDD_SCANB_MENU                  152
#define IDD_SAVE_WND                    153
#define IDR_SCANB_MENU                  154
#define IDD_SWND_FRZE_BTM               155
#define IDD_SWND_RUN_BTM                156
#define IDD_TEXT_DLG                    166
#define IDD_REPORT_DLG                  167
#define IDD_DCINFO_DLG                  168
#define IDD_PTINFO_DLG                  169
#define IDD_PROCESS_DLG                 170
#define IDI_ICON1                       174
#define IDI_ICON_BUTTER                 175
#define IDI_START_ICON                  179
#define IDB_START_BITMAP                180
#define IDB_TEST_BITMAP                 181
#define IDD_START_DIALOG                182
#define IDD_EDITIMG_DLG                 183
#define IDD_SCANOVER_DLG                184
#define IDB_PNG1                        185
#define IDB_ICON_PNG                    185
#define IDI_UP_ICO                      188
#define IDI_DOWN_ICO                    189
#define IDD_REPORTINFO_DLG              190
#define IDB_ICON_PNG2                   191
#define IDB_LINE_PNG                    192
#define IDB_CURVE_PNG                   193
#define IDB_SRADIO_PNG                  194
#define IDB_URADIO_PNG                  195
#define IDC_START_BTN                   1000
#define IDC_UPDATE_BTN                  1001
#define IDC_FILE_BTN                    1001
#define IDC_MENU_BTN                    1002
#define IDC_SET_BTN                     1002
#define IDC_PATIENT_BTN                 1002
#define IDC_TEACH_BTN                   1003
#define IDC_DOCTOR_BTN                  1003
#define IDC_OPERATE_BTN                 1004
#define IDC_CLOSE_BTN                   1004
#define IDC_MODE_BTN                    1005
#define IDC_SCANB_MENU                  1006
#define IDC_STATE_BTN                   1007
#define IDC_SAVE_BTN                    1008
#define IDC_LIST_BTN                    1009
#define IDC_FREQ_STATIC                 1010
#define IDC_FPS_STATIC                  1011
#define IDC_ABOUT_UBTN                  1011
#define IDC_FREQ_SET                    1012
#define IDC_ABOUT_UBTN2                 1012
#define IDC_ICON_BTN                    1012
#define IDC_FPS_SET                     1013
#define IDC_CHECK2                      1014
#define IDC_LEFT_BTN                    1014
#define IDC_RADIO2                      1015
#define IDC_ADD_BTN                     1015
#define IDC_DEPTH_STATIC                1016
#define IDC_ADD_BTN2                    1016
#define IDC_TEXT_BTN                    1016
#define IDC_CUT_BTN                     1017
#define IDC_SET_DEPTH                   1017
#define IDC_DEPTH_SET                   1018
#define IDC_GRAY_BMP                    1019
#define IDC_SCANB_FILE                  1020
#define IDC_NET_BTN                     1020
#define IDC_SCANB_OPERA                 1021
#define IDC_BTN_NORMAL                  1021
#define IDC_EVALUE_BTN                  1021
#define IDC_SCANB_TEACH                 1022
#define IDC_BTN_BLOOD                   1022
#define IDC_SCANB_PUNC                  1023
#define IDC_BTN_AREA                    1023
#define IDC_BTN_ORGAN                   1023
#define IDC_SCANB_SPEICAL               1024
#define IDC_BTN_ARRW                    1024
#define IDC_BTN_MUS                     1024
#define IDC_SCANB_SET                   1025
#define IDC_BTN_ANGLE                   1025
#define IDC_SCANB_ABOUT                 1026
#define IDC_BTN_CIR                     1026
#define IDC_BTN_TEXT                    1027
#define IDC_BTN_LAST                    1028
#define IDC_BTN_ALL                     1029
#define IDC_BTN_LEN                     1030
#define IDC_SLIDER_MOIVE                1031
#define IDC_BTN_PLAY                    1032
#define IDC_BTN_MLIST                   1033
#define IDC_BTN_ADD                     1034
#define IDC_BTN_DEC                     1035
#define IDC_BTN_TEST                    1038
#define IDC_BTN_LOCAL                   1039
#define IDC_RADIO_LINE                  1039
#define IDC_RADIO_CURVE                 1040
#define IDC_BTN_LINE                    1041
#define IDC_BTN_CARVE                   1042
#define IDC_EDIT_TEXT                   1042
#define IDC_BUTTON1                     1043
#define IDC_BUTTON2                     1044
#define IDC_STATIC_HARWARE              1044
#define IDC_DELETE_BTN                  1044
#define IDC_PHOTO_BTN                   1044
#define IDC_GIVEUP_BTN                  1044
#define IDC_BUTTON3                     1045
#define IDC_STATIC_SOFTWARE             1045
#define IDC_MODIFY_BTN                  1045
#define IDC_SEARCH_BTN                  1046
#define IDC_CANCEL_BTN                  1046
#define IDC_SEND_BTN                    1046
#define IDC_SELECT_BTN                  1047
#define IDC_DELETE_BTN1                 1047
#define IDC_DOCTOR_SELECT_BTN           1047
#define IDC_TEXT_STATIC                 1048
#define IDC_DIS_STATIC                  1048
#define IDC_EXIT_BTN                    1048
#define IDC_SEND_BTN3                   1048
#define IDC_PATIENT_SELECT_BTN          1048
#define IDC_SELECTD_BTN                 1049
#define IDC_INPUT_EDIT                  1050
#define IDC_EXPORT_BTN                  1051
#define IDC_REPORT_STATIC               1052
#define IDC_COMPARE_BTN                 1053
#define IDC_MAC_STATIC                  1053
#define IDC_MAN_RADIO                   1057
#define IDC_WOMAN_RADIO                 1058
#define IDC_MOTEXT_STATIC               1059
#define IDC_ID_EDIT                     1060
#define IDC_BIRTHDAY_EDIT               1062
#define IDC_HISTORY_EDIT                1063
#define IDC_DUTIES_EDIT                 1064
#define IDC_NAME_EDIT                   1065
#define IDC_PHONE_EDIT                  1066
#define IDC_EMAIL_EDIT                  1067
#define IDC_COMPANY_EDIT                1068
#define IDC_LIST1                       1069
#define IDC_LIST2                       1071
#define IDC_PROGRESS1                   1072
#define IDC_MAIN_PROGRESS               1073
#define IDC_PROGRESS_TEXT               1074
#define IDC_THUMB_LIST                  1075
#define IDC_OTHERS_EDIT                 1076
#define IDC_SEARCH_BTN1                 1076
#define IDC_EXIT_BTN1                   1077
#define IDC_MODIFY_BTN1                 1078
#define IDC_INPUT_EDIT1                 1079
#define IDC_SELECTD_BTN1                1080
#define IDC_CANCEL_BTN1                 1081
#define IDC_EXPORT_BTN1                 1082
#define IDC_COMPARE_BTN1                1083
#define IDC_PATIENT_STATIC              1084
#define IDC_SCAN_STATIC                 1085
#define ID_X_32771                      32771
#define ID_X_32772                      32772
#define ID_X_32773                      32773
#define ID_X_32774                      32774
#define ID_X_32775                      32775
#define ID_X_32776                      32776
#define ID_X_32777                      32777
#define ID_X_32778                      32778
#define ID_X_32779                      32779
#define ID_X_32780                      32780
#define ID_X_32781                      32781
#define ID_X_32782                      32782
#define ID_X_32783                      32783
#define ID_X_32784                      32784

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        196
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1086
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
